import type { Metadata } from "next";
import "./globals.css";
import s from "./globals.module.scss";
import Sidebar from "../components/Sidebar/Sidebar";
import Topbar from "../components/Topbar/Topbar";
import { raleway } from "@/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        <div className={s.appContainer}>
          <Sidebar />
          <div className={s.mainContent}>
            {/* <Topbar /> */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
